name: dbeaver # you probably want to 'snapcraft register <name>'
version: '4.3.3.1'
summary: Universal SQL Client 
description: |
  Free multi-platform database tool for developers, SQL programmers, database administrators and analysts. Supports all popular databases: MySQL, PostgreSQL, MariaDB, SQLite, Oracle, DB2, SQL Server, Sybase, MS Access, Teradata, Firebird, Derby, etc.
icon: snap/gui/dbeaver.png

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  dbeaver:
    command: desktop-launch $SNAP/dbeaver -data $SNAP_USER_DATA
    # desktop entry not needed when desktop file provided from the snap/gui folder
    #desktop: meta/gui/dbeaver.desktop
    plugs: [home, network, x11, unity7, wayland]


parts:
  dbeaver:
    source: https://github.com/dbeaver/dbeaver.git
    plugin: maven
    # override plugin build step. Plugin build expects a jar in the end which causes an error.
    build: |
      mvn package
    #  export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
    # Reorganize the built files for easier handling
    #organize:
    #  product/standalone/target/products/org.jkiss.dbeaver.core.product/linux/gtk/x86_64/dbeaver: dbeaver
    # if i have understood this correct, this below will make the files available in the snap root.
    #filesets:
    #   binaries:
    #    - dbeaver/*
    # copy output of build to root stage directory
    #stage:
    #  - $binaries
    #prime:
    #  - $binaries
    maven-targets:
      - gui
    maven-options:
      - -DskipTests
    after:
      - desktop-glib-only
    build-packages:
    - ca-certificates
    - ca-certificates-java    
    stage-packages: 
      - libgdk-pixbuf2.0-dev
      - libgdk-pixbuf2.0-0
    install: |
      echo "+++++++++++++++++++++++++++++"
      # trying to copy everything unde 
      cp -r product/standalone/target/products/org.jkiss.dbeaver.core.product/linux/gtk/x86_64/dbeaver/. $SNAPCRAFT_PART_INSTALL/
      
      # The specified command 'dbeaver' defined in the app 'dbeaver' does not exist or is not executable
      echo "empty install"
      
      # sed -i 's|Icon=.*|Icon=/dbeaver.png|g' $SNAPCRAFT_PART_INSTALL/product/standalone/target/products/dbeaver.desktop
      
      
      # chmod: cannot access 'dbeaver': No such file or directory 
      # chmod +x dbeaver    

